apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"go-web-app"},"name":"go-web-app","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"go-web-app"},"type":"ClusterIP"}}
  creationTimestamp: "2025-05-17T06:29:56Z"
  labels:
    app: go-web-app
  name: go-web-app
  namespace: default
  resourceVersion: "6841"
  uid: 07a6db60-9e82-46f1-80b3-40082a8e5873
spec:
  clusterIP: 10.100.190.179
  clusterIPs:
  - 10.100.190.179
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-web-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
